joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.3
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0  # Change the axis for yaw control to the right joystick (e.g., axis 3)
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true

# Add the following parameters to set maximum velocities
  # linear_max_velocity: 0.2
  # angular_max_velocity: 0.4 